import './globals.css'
import { Inter } from 'next/font/google';
import { IBM_Plex_Mono } from 'next/font/google';
import styles from "./page.module.scss";
import CategoriesSection from "./CategoriesSection/CategoriesSection";
import Navigation from "./Components/Navigation/Navigation";

const inter = Inter({ subsets: ['latin'] })
const ibm = IBM_Plex_Mono({ subsets: ['latin'], weight: ["200", "400", "600", "700"] });


export const metadata = {
  title: 'Hawaii-Tour',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={ibm.className}>
        <div className={styles.container}>

          <div className={styles.header}>
            <Navigation />
            <div className={styles.welcome}>Welcome </div>
            <div className={styles.welcome}> to Hawaii</div>
          </div>
          {children}
          {    /* @ts-expect-error Async Server Component */}
          <CategoriesSection />
        </div>
      </body>
    </html>
  )
}
